//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngekiFumenEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    public sealed partial class AudioPlayerToolViewerSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static AudioPlayerToolViewerSetting defaultInstance = ((AudioPlayerToolViewerSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AudioPlayerToolViewerSetting())));
        
        public static AudioPlayerToolViewerSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResampleSize {
            get {
                return ((int)(this["ResampleSize"]));
            }
            set {
                this["ResampleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public float WaveformVecticalScale {
            get {
                return ((float)(this["WaveformVecticalScale"]));
            }
            set {
                this["WaveformVecticalScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DurationMsPerPixel {
            get {
                return ((float)(this["DurationMsPerPixel"]));
            }
            set {
                this["DurationMsPerPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public float CurrentTimeXOffset {
            get {
                return ((float)(this["CurrentTimeXOffset"]));
            }
            set {
                this["CurrentTimeXOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableWaveformDisplay {
            get {
                return ((bool)(this["EnableWaveformDisplay"]));
            }
            set {
                this["EnableWaveformDisplay"] = value;
            }
        }
    }
}
