//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngekiFumenEditor.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class AudioPlayerToolViewerSetting : global::System.Configuration.ApplicationSettingsBase {

        private static AudioPlayerToolViewerSetting defaultInstance = ((AudioPlayerToolViewerSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AudioPlayerToolViewerSetting())));

        public static AudioPlayerToolViewerSetting Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResampleSize {
            get {
                return ((int)(this["ResampleSize"]));
            }
            set {
                this["ResampleSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public float WaveformVecticalScale {
            get {
                return ((float)(this["WaveformVecticalScale"]));
            }
            set {
                this["WaveformVecticalScale"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DurationMsPerPixel {
            get {
                return ((float)(this["DurationMsPerPixel"]));
            }
            set {
                this["DurationMsPerPixel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public float CurrentTimeXOffset {
            get {
                return ((float)(this["CurrentTimeXOffset"]));
            }
            set {
                this["CurrentTimeXOffset"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableWaveformDisplay {
            get {
                return ((bool)(this["EnableWaveformDisplay"]));
            }
            set {
                this["EnableWaveformDisplay"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LimitFPS {
            get {
                return ((int)(this["LimitFPS"]));
            }
            set {
                this["LimitFPS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int WaveformBodyLineWidth {
            get {
                return ((int)(this["WaveformBodyLineWidth"]));
            }
            set {
                this["WaveformBodyLineWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int WaveformHoldLineWidth {
            get {
                return ((int)(this["WaveformHoldLineWidth"]));
            }
            set {
                this["WaveformHoldLineWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int WaveformMarkerLineWidth {
            get {
                return ((int)(this["WaveformMarkerLineWidth"]));
            }
            set {
                this["WaveformMarkerLineWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableWaveformBlockPrerender {
            get {
                return ((bool)(this["EnableWaveformBlockPrerender"]));
            }
            set {
                this["EnableWaveformBlockPrerender"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4194303")]
        public int SoundControlMask {
            get {
                return ((int)(this["SoundControlMask"]));
            }
            set {
                this["SoundControlMask"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SoundVolumes {
            get {
                return ((string)(this["SoundVolumes"]));
            }
            set {
                this["SoundVolumes"] = value;
            }
        }
    }
}
