//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngekiFumenEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class DefaultWaveformSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultWaveformSettings defaultInstance = ((DefaultWaveformSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultWaveformSettings())));
        
        public static DefaultWaveformSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowObjectPlaceLine {
            get {
                return ((bool)(this["ShowObjectPlaceLine"]));
            }
            set {
                this["ShowObjectPlaceLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWaveform {
            get {
                return ((bool)(this["ShowWaveform"]));
            }
            set {
                this["ShowWaveform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTimingLine {
            get {
                return ((bool)(this["ShowTimingLine"]));
            }
            set {
                this["ShowTimingLine"] = value;
            }
        }
    }
}
