//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngekiFumenEditor.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class DefaultWaveformSettings : global::System.Configuration.ApplicationSettingsBase {

        private static DefaultWaveformSettings defaultInstance = ((DefaultWaveformSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultWaveformSettings())));

        public static DefaultWaveformSettings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowObjectPlaceLine {
            get {
                return ((bool)(this["ShowObjectPlaceLine"]));
            }
            set {
                this["ShowObjectPlaceLine"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWaveform {
            get {
                return ((bool)(this["ShowWaveform"]));
            }
            set {
                this["ShowWaveform"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTimingLine {
            get {
                return ((bool)(this["ShowTimingLine"]));
            }
            set {
                this["ShowTimingLine"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16, 16, 16")]
        public global::System.Drawing.Color WaveformBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["WaveformBackgroundColor"]));
            }
            set {
                this["WaveformBackgroundColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 149, 237")]
        public global::System.Drawing.Color WaveformFillColor {
            get {
                return ((global::System.Drawing.Color)(this["WaveformFillColor"]));
            }
            set {
                this["WaveformFillColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color WaveformCursorColor {
            get {
                return ((global::System.Drawing.Color)(this["WaveformCursorColor"]));
            }
            set {
                this["WaveformCursorColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color WaveformBeatLineColor {
            get {
                return ((global::System.Drawing.Color)(this["WaveformBeatLineColor"]));
            }
            set {
                this["WaveformBeatLineColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color WaveformObjectPlaceLineColor {
            get {
                return ((global::System.Drawing.Color)(this["WaveformObjectPlaceLineColor"]));
            }
            set {
                this["WaveformObjectPlaceLineColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191, 255, 255, 0")]
        public global::System.Drawing.Color WaveformHoldLineColor {
            get {
                return ((global::System.Drawing.Color)(this["WaveformHoldLineColor"]));
            }
            set {
                this["WaveformHoldLineColor"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRhythmCurve {
            get {
                return ((bool)(this["ShowRhythmCurve"]));
            }
            set {
                this["ShowRhythmCurve"] = value;
            }
        }



        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float RhythmCurveGamma {
            get {
                return ((float)(this["RhythmCurveGamma"]));
            }
            set {
                this["RhythmCurveGamma"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public float RhythmCurveEmphasis {
            get {
                return ((float)(this["RhythmCurveEmphasis"]));
            }
            set {
                this["RhythmCurveEmphasis"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 230, 160")]
        public global::System.Drawing.Color WaveformRhythmCurveColor {
            get {
                return ((global::System.Drawing.Color)(this["WaveformRhythmCurveColor"]));
            }
            set {
                this["WaveformRhythmCurveColor"] = value;
            }
        }





    }
}
