//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngekiFumenEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class EditorGlobalSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static EditorGlobalSetting defaultInstance = ((EditorGlobalSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EditorGlobalSetting())));
        
        public static EditorGlobalSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AutoSaveTimeInterval {
            get {
                return ((int)(this["AutoSaveTimeInterval"]));
            }
            set {
                this["AutoSaveTimeInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsEnableAutoSave {
            get {
                return ((bool)(this["IsEnableAutoSave"]));
            }
            set {
                this["IsEnableAutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UndoActionSavingLimit {
            get {
                return ((int)(this["UndoActionSavingLimit"]));
            }
            set {
                this["UndoActionSavingLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsEnableUndoActionSavingLimit {
            get {
                return ((bool)(this["IsEnableUndoActionSavingLimit"]));
            }
            set {
                this["IsEnableUndoActionSavingLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double JudgeLineOffsetY {
            get {
                return ((double)(this["JudgeLineOffsetY"]));
            }
            set {
                this["JudgeLineOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableXGridMagneticDock {
            get {
                return ((bool)(this["DisableXGridMagneticDock"]));
            }
            set {
                this["DisableXGridMagneticDock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceMagneticDock {
            get {
                return ((bool)(this["ForceMagneticDock"]));
            }
            set {
                this["ForceMagneticDock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceTapHoldMagneticDockToLane {
            get {
                return ((bool)(this["ForceTapHoldMagneticDockToLane"]));
            }
            set {
                this["ForceTapHoldMagneticDockToLane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableTGridMagneticDock {
            get {
                return ((bool)(this["DisableTGridMagneticDock"]));
            }
            set {
                this["DisableTGridMagneticDock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double XGridUnitSpace {
            get {
                return ((double)(this["XGridUnitSpace"]));
            }
            set {
                this["XGridUnitSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public int TGridUnitLength {
            get {
                return ((int)(this["TGridUnitLength"]));
            }
            set {
                this["TGridUnitLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BeatSplit {
            get {
                return ((int)(this["BeatSplit"]));
            }
            set {
                this["BeatSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int XGridDisplayMaxUnit {
            get {
                return ((int)(this["XGridDisplayMaxUnit"]));
            }
            set {
                this["XGridDisplayMaxUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceXGridMagneticDock {
            get {
                return ((bool)(this["ForceXGridMagneticDock"]));
            }
            set {
                this["ForceXGridMagneticDock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public double VerticalDisplayScale {
            get {
                return ((double)(this["VerticalDisplayScale"]));
            }
            set {
                this["VerticalDisplayScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DisplayTimeFormat {
            get {
                return ((int)(this["DisplayTimeFormat"]));
            }
            set {
                this["DisplayTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JudgeLineAlignBeat {
            get {
                return ((bool)(this["JudgeLineAlignBeat"]));
            }
            set {
                this["JudgeLineAlignBeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MouseWheelLength {
            get {
                return ((int)(this["MouseWheelLength"]));
            }
            set {
                this["MouseWheelLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XOffset {
            get {
                return ((double)(this["XOffset"]));
            }
            set {
                this["XOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowXOffsetScrollBar {
            get {
                return ((bool)(this["ShowXOffsetScrollBar"]));
            }
            set {
                this["ShowXOffsetScrollBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableXOffset {
            get {
                return ((bool)(this["EnableXOffset"]));
            }
            set {
                this["EnableXOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdjustPastedObjects {
            get {
                return ((bool)(this["AdjustPastedObjects"]));
            }
            set {
                this["AdjustPastedObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int ParallelCountLimit {
            get {
                return ((int)(this["ParallelCountLimit"]));
            }
            set {
                this["ParallelCountLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentOpenedListStr {
            get {
                return ((string)(this["RecentOpenedListStr"]));
            }
            set {
                this["RecentOpenedListStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecoveryCurrentTimeAfterExecuteAction {
            get {
                return ((bool)(this["RecoveryCurrentTimeAfterExecuteAction"]));
            }
            set {
                this["RecoveryCurrentTimeAfterExecuteAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoopPlayTiming {
            get {
                return ((bool)(this["LoopPlayTiming"]));
            }
            set {
                this["LoopPlayTiming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnablePlaceObjectBeyondAudioDuration {
            get {
                return ((bool)(this["EnablePlaceObjectBeyondAudioDuration"]));
            }
            set {
                this["EnablePlaceObjectBeyondAudioDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-16777216")]
        public int PlayFieldForegroundColor {
            get {
                return ((int)(this["PlayFieldForegroundColor"]));
            }
            set {
                this["PlayFieldForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-16758145")]
        public int PlayFieldBackgroundColor {
            get {
                return ((int)(this["PlayFieldBackgroundColor"]));
            }
            set {
                this["PlayFieldBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnablePlayFieldDrawing {
            get {
                return ((bool)(this["EnablePlayFieldDrawing"]));
            }
            set {
                this["EnablePlayFieldDrawing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableShowPlayerLocation {
            get {
                return ((bool)(this["EnableShowPlayerLocation"]));
            }
            set {
                this["EnableShowPlayerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorHoldLeft {
            get {
                return ((global::System.Drawing.Color)(this["ColorHoldLeft"]));
            }
            set {
                this["ColorHoldLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color ColorHoldCenter {
            get {
                return ((global::System.Drawing.Color)(this["ColorHoldCenter"]));
            }
            set {
                this["ColorHoldCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColorHoldRight {
            get {
                return ((global::System.Drawing.Color)(this["ColorHoldRight"]));
            }
            set {
                this["ColorHoldRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35, 4, 117")]
        public global::System.Drawing.Color ColorHoldWallRight {
            get {
                return ((global::System.Drawing.Color)(this["ColorHoldWallRight"]));
            }
            set {
                this["ColorHoldWallRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("136, 3, 152")]
        public global::System.Drawing.Color ColorHoldWallLeft {
            get {
                return ((global::System.Drawing.Color)(this["ColorHoldWallLeft"]));
            }
            set {
                this["ColorHoldWallLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LimitFPS {
            get {
                return ((int)(this["LimitFPS"]));
            }
            set {
                this["LimitFPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RenderTargetOrderVisibleMap {
            get {
                return ((string)(this["RenderTargetOrderVisibleMap"]));
            }
            set {
                this["RenderTargetOrderVisibleMap"] = value;
            }
        }
    }
}
