//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngekiFumenEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class KeyBindingSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyBindingSetting defaultInstance = ((KeyBindingSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyBindingSetting())));
        
        public static KeyBindingSetting Default {
            get {
                return defaultInstance;
            }
        }
    }
}
