<Project>
    <PropertyGroup>
        <AvaloniaVersion>12.1.1</AvaloniaVersion>
        <AvaloniaDataGridVersion>12.1.2</AvaloniaDataGridVersion>
        <XamlMcpVersion>1.0.0-preview.3</XamlMcpVersion>
        <LLVMVersion>10.0.0-preview.2.25455.1</LLVMVersion>
        <HarfBuzzSharpVersion>8.3.1.3</HarfBuzzSharpVersion>
        <SkiaSharpVersion>3.119.4</SkiaSharpVersion>
        <MsExtVersion>11.0.0-preview.7.26381.103</MsExtVersion>
        <SystemVersion>11.0.0-preview.7.26381.103</SystemVersion>
    </PropertyGroup>

    <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.HarfBuzz" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Controls.ColorPicker" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="$(AvaloniaDataGridVersion)" />

    <PackageVersion Include="AvaloniaDialogs" Version="3.7.1" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="DialogHost.Avalonia" Version="0.12.3" />
    <PackageVersion Include="FluentIcons.Avalonia.Fluent" Version="2.1.337" />

    <PackageVersion Include="HarfBuzzSharp" Version="$(HarfBuzzSharpVersion)" />
    <PackageVersion Include="HarfBuzzSharp.NativeAssets.Linux" Version="$(HarfBuzzSharpVersion)" />
    <PackageVersion Include="HarfBuzzSharp.NativeAssets.macOS" Version="$(HarfBuzzSharpVersion)" />
    <PackageVersion Include="HarfBuzzSharp.NativeAssets.WebAssembly" Version="$(HarfBuzzSharpVersion)" />
    <PackageVersion Include="HarfBuzzSharp.NativeAssets.Win32" Version="$(HarfBuzzSharpVersion)" />

    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.0" />

    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="$(MsExtVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(MsExtVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="$(MsExtVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="$(MsExtVersion)" />
    <PackageVersion Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.9.50" />

    <PackageVersion Include="Microsoft.DotNet.ILCompiler.LLVM" Version="$(LLVMVersion)" />
    <PackageVersion Include="runtime.linux-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="$(LLVMVersion)" />
    <PackageVersion Include="runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="$(LLVMVersion)" />


    <PackageVersion Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.HarfBuzz" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.WebAssembly" Version="$(SkiaSharpVersion)" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="$(SkiaSharpVersion)" />

    <PackageVersion Include="StatusBar.Avalonia" Version="0.0.3" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0" />
    <PackageVersion Include="System.IO.Hashing" Version="$(SystemVersion)" />
    <PackageVersion Include="Xaml.Behaviors" Version="12.0.7" />
    <PackageVersion Include="XamlMcp.Avalonia" Version="$(XamlMcpVersion)" />
    </ItemGroup>
</Project>
