<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.16.0-preview.1" />
        <PackageReference Include="Avalonia.Headless" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.HarfBuzz" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\OngekiFumenEditor.Avalonia\OngekiFumenEditor.Avalonia.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Data\FumenSamples\*.ogkr" />
        <EmbeddedResource Include="Data\FumenSamples\*.nyageki" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="BenchmarkDotNet.Artifacts\**" />
        <EmbeddedResource Remove="BenchmarkDotNet.Artifacts\**" />
        <None Remove="BenchmarkDotNet.Artifacts\**" />
    </ItemGroup>
</Project>
