//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngekiFumenEditor.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OngekiFumenEditor.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 bullet(id:{0}) pallete is NULL 的本地化字符串。
        /// </summary>
        public static string BulletNullPalleteDescription {
            get {
                return ResourceManager.GetString("BulletNullPalleteDescription", resourceCulture);
            }
        }

        
        /// <summary>
        ///   查找类似 After the last Soflan speed change, the speed should return to 1x normally, but now is {0}x. 的本地化字符串。
        /// </summary>
        public static string CheckRuleSoflanProblem {
            get {
                return ResourceManager.GetString("CheckRuleSoflanProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fumen Header Info 的本地化字符串。
        /// </summary>
        public static string HeaderConstMismatch {
            get {
                return ResourceManager.GetString("HeaderConstMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XRESOLUTION({0}) parameter does not match XGrid.ResX({1}) 的本地化字符串。
        /// </summary>
        public static string HeaderConstMismatch2 {
            get {
                return ResourceManager.GetString("HeaderConstMismatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRESOLUTION({0}) parameter does not match TGrid.ResT({1}) 的本地化字符串。
        /// </summary>
        public static string HeaderConstMismatch3 {
            get {
                return ResourceManager.GetString("HeaderConstMismatch3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fumen creator/designer is empty 的本地化字符串。
        /// </summary>
        public static string HeaderConstMismatch4 {
            get {
                return ResourceManager.GetString("HeaderConstMismatch4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Brightness: {0} is not in range [-3, 3] 的本地化字符串。
        /// </summary>
        public static string InvalidBrightness {
            get {
                return ResourceManager.GetString("InvalidBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid ColorId: {0} 的本地化字符串。
        /// </summary>
        public static string InvalidColorId {
            get {
                return ResourceManager.GetString("InvalidColorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Segment of lane is illegal 的本地化字符串。
        /// </summary>
        public static string InvalidConnectablePath {
            get {
                return ResourceManager.GetString("InvalidConnectablePath", resourceCulture);
            }
        }

        
        /// <summary>
        ///   查找类似 Lane block start wall ({0}) is different than end wall ({1}) 的本地化字符串。
        /// </summary>
        public static string LaneBlockOnMultipleWalls {
            get {
                return ResourceManager.GetString("LaneBlockOnMultipleWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing EnemySet(Boss) object. It is recommended to place one to designate the timing of the boss&apos;s appearance 的本地化字符串。
        /// </summary>
        public static string MissingBossEnemySet {
            get {
                return ResourceManager.GetString("MissingBossEnemySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold (Oid:{0}) object is missing the HoldEnd object 的本地化字符串。
        /// </summary>
        public static string MissingEndObject {
            get {
                return ResourceManager.GetString("MissingEndObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} object is missing a reference to a Lane object 的本地化字符串。
        /// </summary>
        public static string MissingRefObject {
            get {
                return ResourceManager.GetString("MissingRefObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} object references a Lane object (laneId:{1}), which does not exist in the fumen. 的本地化字符串。
        /// </summary>
        public static string MissingRefObject2 {
            get {
                return ResourceManager.GetString("MissingRefObject2", resourceCulture);
            }
        }

        
        /// <summary>
        ///   查找类似 The curve lane has not been interpolated yet 的本地化字符串。
        /// </summary>
        public static string NotInterpolatedCurve {
            get {
                return ResourceManager.GetString("NotInterpolatedCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple ITimelineObject objects of the same type ({0}) overlap 的本地化字符串。
        /// </summary>
        public static string ObjectOverlap {
            get {
                return ResourceManager.GetString("ObjectOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple objects of the same type ({0}) overlap 的本地化字符串。
        /// </summary>
        public static string ObjectOverlap2 {
            get {
                return ResourceManager.GetString("ObjectOverlap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object {0} does not align with the meter/time lines. 的本地化字符串。
        /// </summary>
        public static string ObjectTimelineNotAligned {
            get {
                return ResourceManager.GetString("ObjectTimelineNotAligned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected conflicting Soflan duration: {0} and {1} 的本地化字符串。
        /// </summary>
        public static string SoflanConflict {
            get {
                return ResourceManager.GetString("SoflanConflict", resourceCulture);
            }
        }

        
        /// <summary>
        ///   查找类似 Walls on different sides (id:{0}) and (id:{1}) horizontally intersect, collide, or overlap 的本地化字符串。
        /// </summary>
        public static string WallConflict {
            get {
                return ResourceManager.GetString("WallConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wall (id:{0}) Next/End object&apos;s TGrid ({1}) should not be lower than the former ({2}) 的本地化字符串。
        /// </summary>
        public static string WallConflict3 {
            get {
                return ResourceManager.GetString("WallConflict3", resourceCulture);
            }
        }

        
        /// <summary>
        ///   查找类似 {0} object seems not to be placed on the correct lane (id:{1}) 的本地化字符串。
        /// </summary>
        public static string WrongLocation {
            get {
                return ResourceManager.GetString("WrongLocation", resourceCulture);
            }
        }
    }
}
