global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Input;
global using Avalonia.Interactivity;
global using Gekimini.Avalonia.Framework;
global using Gekimini.Avalonia.Framework.Documents;
global using Gekimini.Avalonia.Framework.Menus;
global using Gekimini.Avalonia.Framework.Tools;
global using Gekimini.Avalonia.Framework.UndoRedo;
global using Gekimini.Avalonia.Utils;
global using Gekimini.Avalonia.Utils.MethodExtensions;
global using OngekiFumenEditor.Avalonia;
global using OngekiFumenEditor.Avalonia.Utils;
global using Gemini.Framework.Menus;
global using CommunityToolkit.Mvvm.ComponentModel;
global using OngekiFumenEditor.Avalonia.Models.Settings;
global using Properties = OngekiFumenEditor.Avalonia.Models.Settings;
global using RoutedEventArgs = Avalonia.Interactivity.RoutedEventArgs;
global using MouseWheelEventArgs = Avalonia.Input.PointerWheelEventArgs;
global using FrameworkElement = Avalonia.Controls.Control;
global using UIElement = Avalonia.Visual;
global using ActionExecutionContext = OngekiFumenEditor.Avalonia.Compat.ActionExecutionContext;
global using MouseButtonState = OngekiFumenEditor.Avalonia.Compat.MouseButtonState;
